version: '3.3'

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./front
      dockerfile: ./dev.dockerfile
    volumes:
      - '.:/app'
    ports:
      - "${front_port}:8080"
  products:
    env_file:
      - .env
    build:
      context: ./products
      dockerfile: ./dev.dockerfile
    volumes:
      - '.:/products'
    ports:
      - "${products_port}:3000"
  orders:
    env_file:
      - .env
    build:
      context: ./orders
      dockerfile: ./dev.dockerfile
    volumes:
      - '.:/orders'
    ports:
      - "${orders_port}:3000"
  users:
    env_file:
      - .env
    build:
      context: ./users
      dockerfile: ./dev.dockerfile
    volumes:
      - '.:/users'
    ports:
      - "${users_port}:3000"