version: '3.3'

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./front
      dockerfile: ./dev.dockerfile
    ports:
      - "${front_port}:8080"
  #
  products:
    env_file:
      - .env
    build:
      context: ./products
      dockerfile: ./dev.dockerfile
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - gems:/usr/local/bundle
      - './products:/app'
    ports:
      - "${products_port}:3000"
  #
  orders:
    env_file:
      - .env
    build:
      context: ./orders
      dockerfile: ./dev.dockerfile
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - gems:/usr/local/bundle
      - './orders:/app'
    ports:
      - "${orders_port}:3000"
  #
  users:
    env_file:
      - .env
    build:
      context: users
      dockerfile: ./dev.dockerfile
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - gems:/usr/local/bundle
      - './users:/app'
    ports:
      - "${users_port}:3000"
#
volumes:
  gems: